name: gmPlugin
version: '${project.version}'
main: de.philippcmd.gmplugin.GameModePlugin
api-version: '1.20'
commands:
  gm:
    description: can change the gamemode of players
    usage: "Usage: /gm <1|2|3|4> (Player)"
    permission: gm.use

